import React from "react";
import { Roboto } from "next/font/google";

import StyledComponentsRegistry from "@/app/lib/AntdRegistry";
import { HolidaySearchProvider } from "./contexts/HolidaySearchContext";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <HolidaySearchProvider>
    <html lang="en">
      <body
        className={roboto.className}
        style={{ backgroundColor: "#f5f5f5", margin: "0" }}
      >
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  </HolidaySearchProvider>
);

export default RootLayout;
